sitename: Ondulation
siteurl: 'https://ondulation.github.io'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
  - examples
exclude:
  - README.md
  - LICENSE
  - "*.BAK"
